### ISSUE TITLE
Asking to install node.js and npm 

### ISSUE THREAD

**Issue by frazakram** [raga-ai-hub/ragaai-catalyst#15]
i am running this code in
Windows 10 Home Single Language
Python 3.12.4

It Asking me to install node.js and npm even though its already install i verify it by running node -v and npm -v and  i get v20.17.0 and 10.8.2 respectively. i have attached screenshot of my input 
![image](https://github.com/user-attachments/assets/541dd8fa-15e2-4964-87b3-ac6795824d50)
"""
Error: Node.js and npm are required but not installed.
Please install Node.js and npm to continue:
1. Visit https://nodejs.org/
2. Download and install the LTS version
3. Restart your terminal/command prompt after installation
4. Run this command again
If the issue persists, please raise an issue at: https://github.com/raga-ai-hub/agentneo/issues
"""

**Comment by kiranscaria** [comment]
Resolved in #33
