### ISSUE TITLE
[BUG]: In the dashboard, Inside execution graph, memory usage is negative and values are not as expected

### ISSUE THREAD

**Issue by Ritika1311** [raga-ai-hub/ragaai-catalyst#23]
**Issue Description:**
In the dashboard, under the "Execution Graph" section, the memory usage values are displayed as negative numbers, which is incorrect. Additionally, the memory usage values do not seem to align with the expected resource utilization, leading to discrepancies in understanding the actual memory consumption.

**Steps to Reproduce:**
Go to the dashboard.
Navigate to the "Execution Graph" section.
Observe the memory usage statistics.

**Expected Behavior:**
The memory usage values should accurately reflect the memory consumption in non-negative numbers and match the expected resource utilization during execution.

**Actual Behavior:**
Memory usage is displayed as negative values and is inconsistent with the actual memory usage, leading to confusion.

**Comment by kiranscaria** [comment]
Resolved in #33
