### ISSUE TITLE
[BUG]: example/FinancialAnalysisSystem.ipynb cannot import name 'Execution' from 'agentneo' 

### ISSUE THREAD

**Issue by rahulanand1103** [raga-ai-hub/ragaai-catalyst#47]
ImportError                               Traceback (most recent call last)
Cell In[1], [line 6](vscode-notebook-cell:?execution_count=1&line=6)
      [4](vscode-notebook-cell:?execution_count=1&line=4) import openai
      [5](vscode-notebook-cell:?execution_count=1&line=5) from dotenv import load_dotenv
----> [6](vscode-notebook-cell:?execution_count=1&line=6) from agentneo import AgentNeo, Tracer, Execution
      [8](vscode-notebook-cell:?execution_count=1&line=8) # Load environment variables
      [9](vscode-notebook-cell:?execution_count=1&line=9) load_dotenv("YOUR_ENV_FILE")

ImportError: cannot import name 'Execution' from 'agentneo' (/opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/__init__.py)

**Comment by rehan-ai** [comment]
Which agentneo version are you using?

**Comment by rahulanand1103** [comment]
I updated to version 1.1 from 1.0.3 but am now encountering a new error. Please advise on how to resolve this issue.

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File /opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/tracing/llm_utils.py:13
     [12](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/tracing/llm_utils.py:12) try:
---> [13](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/tracing/llm_utils.py:13)     with open("agentneo/configs/model_costs.json", "r") as file:
     [14](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/tracing/llm_utils.py:14)         config = json.load(file)

FileNotFoundError: [Errno 2] No such file or directory: 'agentneo/configs/model_costs.json'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[1], [line 6](vscode-notebook-cell:?execution_count=1&line=6)
      [4](vscode-notebook-cell:?execution_count=1&line=4) import openai
      [5](vscode-notebook-cell:?execution_count=1&line=5) from dotenv import load_dotenv
----> [6](vscode-notebook-cell:?execution_count=1&line=6) from agentneo import AgentNeo, Tracer, Execution
      [8](vscode-notebook-cell:?execution_count=1&line=8) # Load environment variables
      [9](vscode-notebook-cell:?execution_count=1&line=9) load_dotenv("YOUR_ENV_FILE")

File /opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/__init__.py:1
----> [1](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/__init__.py:1) from .tracing.utils import log_event
      [2](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/__init__.py:2) from .tracing import Tracer
      [3](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/__init__.py:3) from .agentneo import AgentNeo

File /opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/tracing/__init__.py:5
...
     [38](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/importlib/resources/_legacy.py:38) if parent:
---> [39](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/importlib/resources/_legacy.py:39)     raise ValueError(f'{path!r} must be only a file name')
     [40](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/py3.11/lib/python3.11/importlib/resources/_legacy.py:40) return file_name

ValueError: 'configs/model_costs.json' must be only a file name

**Comment by kiranscaria** [comment]
@rahulanand1103 Seems to a file path issue, deploying the fix

**Comment by kiranscaria** [comment]
@rahulanand1103 This issue is fixed in [v1.1.1](https://pypi.org/project/agentneo/1.1.1/)

**Comment by rahulanand1103** [comment]
I can run it. but I get an error.
Sorry to keep bugging you, 

in this code I get the error.
`
exe = Execution(session=neo_session, trace_id=tracer.trace_id)
exe.execute(metric_list=['goal_decomposition_efficiency', 
                         'goal_decomposition_efficiency', 
                         'tool_correctness_metric', 
                         'tool_correctness_metric'])
`


{
 "name": "IndexError",
 "message": "list index out of range",
 "stack": "---------------------------------------------------------------------------
IndexError Traceback (most recent call last)
Cell In[22], line 4
 1 exe = Execution(session=neo_session, trace_id=tracer.trace_id)
 3 # run a single metric
----> 4 exe.execute(metric_list=['goal_decomposition_efficiency',
 5 'goal_decomposition_efficiency',
 6 'tool_correctness_metric',
 7 'tool_correctness_metric'])

File /opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/execution/execution.py:43, in Execution.execute(self, metric_list, config, metadata)
 41 for metric in metric_list:
 42 start_time = datetime.now()
---> 43 result = self._execute_metric(metric, config, metadata)
 44 end_time = datetime.now()
 45 duration = (end_time - start_time).total_seconds()

File /opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/execution/execution.py:65, in Execution._execute_metric(self, metric, config, metadata)
 60 return execute_goal_fulfillment_metric(
 61 trace_json=self.trace_data,
 62 config=config,
 63 )
 64 elif metric == 'tool_correctness_metric':
---> 65 return execute_tool_correctness_metric(
 66 trace_json=self.trace_data,
 67 config=config,
 68 )
 69 elif metric == 'tool_call_success_rate_metric':
 70 return execute_tool_call_success_rate_metric(
 71 trace_json=self.trace_data,
 72 config=config,
 73 )

File /opt/anaconda3/envs/py3.11/lib/python3.11/site-packages/agentneo/execution/metrics/tool_metrics.py:32, in execute_tool_correctness_metric(trace_json, config)
 27 def execute_tool_correctness_metric(
 28 trace_json: Dict[str, Any], config: Dict[str, Any]
 29 ) -> Dict[str, Any]:
 30
 31 # Extract query from the trace
---> 32 query = trace_json["llm_calls"][0]["input_prompt"][0]["content"]
 34 # Find tool calls
 35 tool_calls = trace_json["tool_calls"]

IndexError: list index out of range"
}

**Comment by kiranscaria** [comment]
@rahulanand1103 This error is caused by the metric execution occurring for null traces. Please ensure you are running the metric execution using:

```
exe = Execution(session=neo_session, trace_id=tracer.trace_id)
```

**Comment by rahulanand1103** [comment]
Thanks!
