### ISSUE TITLE
[BUG]: Logging/Serialization Error

### ISSUE THREAD

**Issue by fraz-prod** [raga-ai-hub/ragaai-catalyst#73]
# Bug Report

**Describe the Bug**
 The dashboard is displaying empty arrays for "LLM Call IDs" and "Tool Call IDs" (i.e., "[]"), indicating that no IDs are being captured or returned, which might suggest a failure in tracking or logging these calls

**To Reproduce**
Steps or code snippets to reproduce the behavior, like:
```
1. Install AgentNeo using `pip install agentneo`
2. Run the following code:
   https://github.com/raga-ai-hub/AgentNeo/blob/v1.1/examples/LangGraph/Chatbot.ipynb
3. Launch the dashboard using `launch_dashboard(port=3000)`
4. Observe the error or unexpected behavior.
```

**Expected Behavior**
The dashboard should display populated arrays with relevant 'LLM Call IDs' and 'Tool Call IDs,' reflecting the unique identifiers of each call logged. These arrays should contain IDs for each recorded call, allowing for accurate tracking and referencing rather than showing empty arrays ('[]')

**Actual Behavior**
 The dashboard is displaying empty arrays for "LLM Call IDs" and "Tool Call IDs" (i.e., "[]"), indicating that no IDs are being captured or returned, which might suggest a failure in tracking or logging these calls

**Logs and Screenshots**
If applicable, add logs, stack traces, or screenshots to help explain the issue.
![image](https://github.com/user-attachments/assets/001c3c50-1130-4258-b30b-75d597405f36)

**Environment Details**
- **Operating System**: Windows 10.0.2
- **Python Version**:  3.11.10
- **AgentNeo Version**:  1.1.2
- **Relevant Packages**:  OpenAI SDK 0.9.0, LiteLLM 1.2.3

**AgentNeo Configuration**
Provide any custom configuration settings or code modifications:
```python
# Your custom configuration or code here
```

**Additional Context**
Add any other information about the problem here, such as:
- Network configuration
- Firewall settings
- Previous attempts to fix the issue

**Comment by kiranscaria** [comment]
Resolved in #81
