### ISSUE TITLE
[BUG]: Data Presentation/Error in Metric Reporting

### ISSUE THREAD

**Issue by fraz-prod** [raga-ai-hub/ragaai-catalyst#74]
# Bug Report

**Describe the Bug**
 The result detail for the metric is showing incomplete or improperly formatted JSON data (e.g., {"metric_name":"goal_fulfillment_rate","config":{}...), which may indicate a failure in data serialization or presentation, leading to unclear metric reporting.

**To Reproduce**
Steps or code snippets to reproduce the behavior, like:
```
1. Install AgentNeo using `pip install agentneo`
2. Run the following code:
   https://github.com/raga-ai-hub/AgentNeo/blob/v1.1/examples/LangGraph/Chatbot.ipynb
3. Launch the dashboard using `launch_dashboard(port=3000)`
4. Observe the error or unexpected behavior.
```

**Expected Behavior**
The result detail for each metric should display complete, properly formatted JSON data, with all relevant fields populated and structured accurately. This ensures clear and accurate reporting of metric details, avoiding any truncation or formatting issues that could hinder data interpretation

**Actual Behavior**
 The result detail for the metric is showing incomplete or improperly formatted JSON data (e.g., {"metric_name":"goal_fulfillment_rate","config":{}...), which may indicate a failure in data serialization or presentation, leading to unclear metric reporting.

**Logs and Screenshots**
![image](https://github.com/user-attachments/assets/bcc349e2-7dee-4140-9e2a-d643819793b1)

**Environment Details**
- **Operating System**: Windows 10.0.2
- **Python Version**:  3.11.10
- **AgentNeo Version**:  1.1.2
- **Relevant Packages**:  OpenAI SDK 0.9.0, LiteLLM 1.2.3

**AgentNeo Configuration**
Provide any custom configuration settings or code modifications:
```python
# Your custom configuration or code here
```

**Additional Context**
Add any other information about the problem here, such as:
- Network configuration
- Firewall settings
- Previous attempts to fix the issue

**Comment by kiranscaria** [comment]
Resolved in #84
