### ISSUE TITLE
[BUG]: score key (ascend/descend)

### ISSUE THREAD

**Issue by fraz-prod** [raga-ai-hub/ragaai-catalyst#75]
# Bug Report

**Describe the Bug**
score sorting is not working  after selecting one tracer in evaluation part but it is working when we select all tracer

**To Reproduce**
Steps or code snippets to reproduce the behavior, like:
```
1. Install AgentNeo using `pip install agentneo`
2. Run the following code:
   https://github.com/raga-ai-hub/AgentNeo/blob/v1.1/examples/LangGraph/Chatbot.ipynb
3. Launch the dashboard using `launch_dashboard(port=3000)`
4. Observe the error or unexpected behavior.
```

**Expected Behavior**
The score sorting functionality should work consistently, allowing users to sort scores correctly whether a single tracer or all tracers are selected in the evaluation part. Sorting should apply accurately to the selected tracer's scores to enable reliable score comparison

**Actual Behavior**
score sorting is not working  after selecting one tracer in evaluation part but it is working when we select all tracer
**Logs and Screenshots**
![image](https://github.com/user-attachments/assets/6350c1da-214b-4de9-b137-55fc9ec4754d)

**Environment Details**
- **Operating System**: Windows 10.0.2
- **Python Version**:  3.11.10
- **AgentNeo Version**:  1.1.2
- **Relevant Packages**:  OpenAI SDK 0.9.0, LiteLLM 1.2.3

**AgentNeo Configuration**
Provide any custom configuration settings or code modifications:
```python
# Your custom configuration or code here
```

**Additional Context**
Add any other information about the problem here, such as:
- Network configuration
- Firewall settings
- Previous attempts to fix the issue

**Comment by kiranscaria** [comment]
Resolved in v1.2
