### ISSUE TITLE
[BUG]: metric distrubution is empty

### ISSUE THREAD

**Issue by fraz-prod** [raga-ai-hub/ragaai-catalyst#77]
# Bug Report

**Describe the Bug**
there is no graph showing in metric distrbution 

**To Reproduce**
Steps or code snippets to reproduce the behavior, like:
```
1. Install AgentNeo using `pip install agentneo`
2. Run the following code:
   https://github.com/raga-ai-hub/AgentNeo/blob/v1.1/examples/LangGraph/Chatbot.ipynb
3. Launch the dashboard using `launch_dashboard(port=3000)`
4. Observe the error or unexpected behavior.
```

**Expected Behavior**
The metric distribution section should display a graph visualizing the distribution of metrics, providing a clear and informative representation of the data. The graph should be generated based on the available metrics and should not be absent or empty, allowing users to analyze and interpret the metric trends effectively

**Actual Behavior**
there is no graph showing in metric distrbution 

**Logs and Screenshots**
![image](https://github.com/user-attachments/assets/14bfeca5-1408-480c-a519-77e29c8cd6fb)

**Environment Details**
- **Operating System**: Windows 10.0.2
- **Python Version**:  3.11.10
- **AgentNeo Version**:  1.1.2
- **Relevant Packages**:  OpenAI SDK 0.9.0, LiteLLM 1.2.3

**AgentNeo Configuration**
Provide any custom configuration settings or code modifications:
```python
# Your custom configuration or code here
```

**Additional Context**
Add any other information about the problem here, such as:
- Network configuration
- Firewall settings
- Previous attempts to fix the issue

**Comment by kiranscaria** [comment]
Resolved in #82
