### ISSUE TITLE
[BUG]: Launch Dashboard error 

### ISSUE THREAD

**Issue by Bharanikarthick2608** [raga-ai-hub/ragaai-catalyst#85]
# Bug Report

**Describe the Bug**
The function launch_dashboard in the AgentNeo package fails with an error, UnboundLocalError: local variable 'free_port' referenced before assignment. This occurs when the dashboard is launched, and the initially specified port is free. The error appears to be due to an incorrect logging reference to free_port instead of port in the final logging message.

**To Reproduce**
Install AgentNeo using pip install agentneo
Run the following code
from agentneo.server.dashboard import launch_dashboard
launch_dashboard(port=3000)

**Expected Behavior**
The dashboard should launch successfully on the specified port without errors, and the log message should show
**Actual Behavior**
Throwing  UnboundLocalError: local variable 'free_port' referenced before assignment
**Logs and Screenshots**
![Screenshot 2024-10-29 034143](https://github.com/user-attachments/assets/47cbb7ef-b261-4527-930b-8068f28b67d1)

**Environment Details**
Operating System: Windows 11
Python Version: 3.12
AgentNeo Version: v1.2

**AgentNeo Configuration**
N/A

**Additional Context**
I modified the launch_dashboard function to improve port management. Specifically, I added a conditional check to detect if the initially specified port is busy, and if so, it finds an available port using the find_free_port function. If the port is free, a log entry confirms its availability. Additionally, I updated the final log message to accurately reference port instead of free_port. After making these changes, the dashboard successfully launched and is now working as expected. All other code remains unchanged.

**Comment by kiranscaria** [comment]
Resolved in 199c2ed392c56157873941dce7b02e3710c4e56e
